// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Theme$ExampleApp = require("./Theme.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var Toolbar$ExampleApp = require("./components/Toolbar.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");

var container = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#181818"])),
      /* :: */[
        Style$BsReactNative.height(/* Pct */Block.__(1, [100])),
        /* [] */0
      ]
    ]);

var welcome = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.textAlign(/* Center */3),
      /* :: */[
        Style$BsReactNative.margin(/* Pt */Block.__(0, [10])),
        Theme$ExampleApp.Styles[/* text */0]
      ]
    ]);

var instructions = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.textAlign(/* Center */3),
      /* :: */[
        Style$BsReactNative.color(/* String */Block.__(0, ["#333333"])),
        /* :: */[
          Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [5])),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* container */container,
  /* welcome */welcome,
  /* instructions */instructions
];

var component = ReasonReact.statelessComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[container], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                              ReasonReact.element(/* None */0, /* None */0, Toolbar$ExampleApp.make(/* array */[])),
                              ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[welcome], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Welcome to React-Native"]))]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var app = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.Styles = Styles;
exports.component = component;
exports.make = make;
exports.app = app;
/* container Not a pure module */
