// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");

var text_000 = Style$BsReactNative.color(/* String */Block.__(0, ["#AAABAC"]));

var text_001 = /* :: */[
  Style$BsReactNative.fontSize(/* Float */Block.__(0, [20])),
  /* [] */0
];

var text = /* :: */[
  text_000,
  text_001
];

var Styles = /* module */[/* text */text];

exports.Styles = Styles;
/* text Not a pure module */
